version: 4.0.78
steps:
  - prompt: Click on the settings icon.
    commands:
      - command: hover-image
        description: settings icon in the header
        action: click
  - prompt: Change a user preference, such as theme or language.
    commands:
      - command: hover-text
        text: Bored Waiting?
        description: checkbox for Bored Waiting option
        action: click
  - prompt: >-
      Assert that the preference change is applied.  # Use the content of the
      file from the environment
    commands:
      - command: assert
        expect: the "Bored Waiting?" option is checked
